In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
epsilon = np.array([
10 ** p
for p in np.arange(0, -11, -1, dtype = float)])

epsilon

array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09, 1.e-10])

In [6]:
a = 3
a - epsilon

array([2.        , 2.9       , 2.99      , 2.999     , 2.9999    ,
       2.99999   , 2.999999  , 2.9999999 , 2.99999999, 3.        ,
       3.        ])

In [8]:
a + epsilon[::-1]

array([3.        , 3.        , 3.00000001, 3.0000001 , 3.000001  ,
       3.00001   , 3.0001    , 3.001     , 3.01      , 3.1       ,
       4.        ])

In [9]:
np.append(a - epsilon, a + epsilon[::-1])

array([2.        , 2.9       , 2.99      , 2.999     , 2.9999    ,
       2.99999   , 2.999999  , 2.9999999 , 2.99999999, 3.        ,
       3.        , 3.        , 3.        , 3.00000001, 3.0000001 ,
       3.000001  , 3.00001   , 3.0001    , 3.001     , 3.01      ,
       3.1       , 4.        ])

In [10]:
x = np.append(a - epsilon, a + epsilon[::-1])

In [15]:
y = x ** 3

In [16]:
for i in zip(x, y):
    print(i)

(2.0, 8.0)
(2.9, 24.389)
(2.99, 26.730899000000004)
(2.999, 26.973008999000005)
(2.9999, 26.997300089998994)
(2.99999, 26.999730000899998)
(2.999999, 26.999973000008996)
(2.9999999, 26.999997300000093)
(2.99999999, 26.999999730000003)
(2.999999999, 26.999999972999998)
(2.9999999999, 26.9999999973)
(3.0000000001, 27.0000000027)
(3.000000001, 27.000000027000002)
(3.00000001, 27.00000027)
(3.0000001, 27.000002700000085)
(3.000001, 27.000027000009005)
(3.00001, 27.000270000900002)
(3.0001, 27.002700090001007)
(3.001, 27.027009000999996)
(3.01, 27.270900999999995)
(3.1, 29.791000000000004)
(4.0, 64.0)


In [19]:
def get_limit(f, a):
    epsilon = np.array([
        10 ** p
        for p in np.arange(0, -11, -1, dtype = float)])
    
    x = np.append(a - epsilon, (a + epsilon)[::-1])
    y = f(x)
    return y

print(get_limit(lambda x: x ** 2, 3))
print(get_limit(lambda x: x ** 2 + 3 * x, 2))
print(get_limit(lambda x: np.sin(x), 0))

[ 4.          8.41        8.9401      8.994001    8.99940001  8.99994
  8.999994    8.9999994   8.99999994  8.99999999  9.          9.
  9.00000001  9.00000006  9.0000006   9.000006    9.00006     9.00060001
  9.006001    9.0601      9.61       16.        ]
[ 4.          9.31        9.9301      9.993001    9.99930001  9.99993
  9.999993    9.9999993   9.99999993  9.99999999 10.         10.
 10.00000001 10.00000007 10.0000007  10.000007   10.00007    10.00070001
 10.007001   10.0701     10.71       18.        ]
[-8.41470985e-01 -9.98334166e-02 -9.99983333e-03 -9.99999833e-04
 -9.99999998e-05 -1.00000000e-05 -1.00000000e-06 -1.00000000e-07
 -1.00000000e-08 -1.00000000e-09 -1.00000000e-10  1.00000000e-10
  1.00000000e-09  1.00000000e-08  1.00000000e-07  1.00000000e-06
  1.00000000e-05  9.99999998e-05  9.99999833e-04  9.99983333e-03
  9.98334166e-02  8.41470985e-01]


In [18]:
def calculate_derivative(f, a, h = 1e-7):
    return (f(a + h) - f(a)) / h

print(calculate_derivative(lambda x: 3 * x**2 + 5 * x - 8, 3))

# 23.00000026878024

23.00000026878024


In [20]:
x_zero = 3

EPSILON = 1e-7
numerator = (x_zero + EPSILON) ** 2 - x_zero ** 2
derivative = numerator / EPSILON

In [21]:
derivative

6.000000087880153

In [26]:
x_old = 0
x_new = 6
step_size = 0.01
precision = 0.00001

def df(x):
    # f'(x^4 - 3x^3 + 2) = 4x^3 - 9x^2
    y = 4 * x ** 3 - 9 * x ** 2
    print("y = ", y)
    return y

while abs(x_new - x_old) > precision:
    print(x_old)
    print(x_new)
    x_old = x_new
    x_new += - step_size * df(x_old)

print("The local minimum occurs at ", + x_new)

0
6
y =  540
6
0.5999999999999996
y =  -2.3759999999999977
0.5999999999999996
0.6237599999999996
y =  -2.5309273140264934
0.6237599999999996
0.6490692731402646
y =  -2.6978303236479175
0.6490692731402646
0.6760475763767438
y =  -2.87743891221372
0.6760475763767438
0.704821965498881
y =  -3.0704171104943887
0.704821965498881
0.7355261366038248
y =  -3.277313550751958
0.7355261366038248
0.7682992721113444
y =  -3.49849557572861
0.7682992721113444
0.8032842278686305
y =  -3.734063397888848
0.8032842278686305
0.840624861847519
y =  -3.9837406582347437
0.840624861847519
0.8804622684298664
y =  -4.2467382301092105
0.8804622684298664
0.9229296507309586
y =  -4.521589529960476
0.9229296507309586
0.9681455460305634
y =  -4.805958449122873
0.9681455460305634
1.016205130521792
y =  -5.096425942090499
1.016205130521792
1.067169389942697
y =  -5.3882689590343515
1.067169389942697
1.1210520795330405
y =  -5.6752562614243125
1.1210520795330405
1.1778046421472836
y =  -5.94949956770484
1.1778046421472