In [1]:
import numpy as np

In [3]:
my_table = np.array([
    [1, 2, 3],
    [1, -5, 0],
    [-2.5, 0, 42]
])
my_table

array([[ 1. ,  2. ,  3. ],
       [ 1. , -5. ,  0. ],
       [-2.5,  0. , 42. ]])

In [7]:
A = np.array([
    [2, 3, 7],
    [8, 9, 1]
])
B = np.array([
    [1, -3, 0],
    [2, -4, 1]
])

# print(A + B)
# print(2 * A)
# print(A * B) # Element-wise multiplication
# print(A.dot(B)) # Error: incompatible dimensions
# print(A.dot(B.T)) # Matrix multiplication

In [13]:
A.dot(B.T)

array([[ -7,  -1],
       [-19, -19]])

In [14]:
A @ B.T

array([[ -7,  -1],
       [-19, -19]])